## Exemplo-de-Projeto-Problema-de-negocio-Wine-Vinho-XGBoost-26-setembro-2023

## Prever a qualidade de vinho, dado as sua características aferidas

In [1]:
import warnings
warnings.filterwarnings('ignore')

In [2]:
!pip install -q huggingface_hub

In [3]:
!pip install -q joblib

In [4]:
%%time
from huggingface_hub import hf_hub_url, cached_download
import joblib
import pandas as pd

REPO_ID = "julien-c/wine-quality"
FILENAME = "sklearn_model.joblib"


model = joblib.load(cached_download(
    hf_hub_url(REPO_ID, FILENAME)
))
model

CPU times: user 1.41 s, sys: 569 ms, total: 1.98 s
Wall time: 4.43 s


Pipeline(steps=[('scaler', StandardScaler()), ('SVM', SVC())])

In [5]:
REPO_ID

'julien-c/wine-quality'

In [6]:
data_file = cached_download(
    hf_hub_url(REPO_ID, "winequality-red.csv")
)
!ls -ilha *.csv

8926224223 -rw-r--r--@ 1 valencar  staff   1.9K Sep  4 18:08 Estados_idh.csv
8915271421 -rw-r--r--@ 1 valencar  staff   2.0M May 16 11:13 brasil2023.csv
8871475201 -rw-r--r--@ 1 valencar  staff   111K May 10  2022 covid19-22-janeiro-2022.csv
8871475202 -rw-r--r--@ 1 valencar  staff    90K May 10  2022 covid19-23-dez-2021.csv
8915273355 -rw-r--r--@ 1 valencar  staff   2.2K May 18 11:56 estados.csv
8926253444 -rw-r--r--@ 1 valencar  staff   1.9K Sep  5 12:06 estados_idh (Conflitos entre maiúsculas e minúsculas 1).csv
8926253442 -rw-r--r--@ 1 valencar  staff   1.9K Sep  5 12:05 estados_idh (Conflitos entre maiúsculas e minúsculas).csv
8926253443 -rw-r--r--@ 1 valencar  staff   1.9K Sep  5 12:06 estados_idh2.csv
8871475203 -rw-r--r--@ 1 valencar  staff    29K May 10  2022 mapa_mundo_covid19-4-fevereiro-2022.csv
8915271411 -rw-r--r--@ 1 valencar  staff   5.6M May 16 11:16 prouni.csv
8871475204 -rw-r--r--@ 1 valencar  staff   242B May 10  2022 ratings_saida.csv


In [7]:
data_file

'/Users/valencar/.cache/huggingface/hub/f3aec5dda07574be505d0067cc4cadea8b8224353f8a987c809664443c6f6352.1e69d60fe81c6951c1cba05ec464e9f3bfc20f391de2b2e40d0b6573081b69b3'

In [8]:
#head `/home/valencar/.cache/huggingface/hub/f3aec5dda07574be505d0067cc4cadea8b8224353f8a987c809664443c6f6352.1e69d60fe81c6951c1cba05ec464e9f3bfc20f391de2b2e40d0b6573081b69b3`

In [9]:
winedf = pd.read_csv(data_file, sep=";")

print(len(winedf))
winedf.head()

1599


fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0            7.4              0.70         0.00             1.9      0.076   
1            7.8              0.88         0.00             2.6      0.098   
2            7.8              0.76         0.04             2.3      0.092   
3           11.2              0.28         0.56             1.9      0.075   
4            7.4              0.70         0.00             1.9      0.076   

   free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                 11.0                  34.0   0.9978  3.51       0.56   
1                 25.0                  67.0   0.9968  3.20       0.68   
2                 15.0                  54.0   0.9970  3.26       0.65   
3                 17.0                  60.0   0.9980  3.16       0.58   
4                 11.0                  34.0   0.9978  3.51       0.56   

   alcohol  quality  
0      9.4        5  
1      9.8        5  
2      9.8        5  
3      9.8        6  
4      9.4        5

In [79]:
winedf.to_csv('vinhos_classificacao.csv', index=False)
!ls -ilah *.csv

8926224223 -rw-r--r--@ 1 valencar  staff   1.9K Sep  4 18:08 Estados_idh.csv
8915271421 -rw-r--r--@ 1 valencar  staff   2.0M May 16 11:13 brasil2023.csv
8871475201 -rw-r--r--@ 1 valencar  staff   111K May 10  2022 covid19-22-janeiro-2022.csv
8871475202 -rw-r--r--@ 1 valencar  staff    90K May 10  2022 covid19-23-dez-2021.csv
8915273355 -rw-r--r--@ 1 valencar  staff   2.2K May 18 11:56 estados.csv
8926253444 -rw-r--r--@ 1 valencar  staff   1.9K Sep  5 12:06 estados_idh (Conflitos entre maiúsculas e minúsculas 1).csv
8926253442 -rw-r--r--@ 1 valencar  staff   1.9K Sep  5 12:05 estados_idh (Conflitos entre maiúsculas e minúsculas).csv
8926253443 -rw-r--r--@ 1 valencar  staff   1.9K Sep  5 12:06 estados_idh2.csv
8871475203 -rw-r--r--@ 1 valencar  staff    29K May 10  2022 mapa_mundo_covid19-4-fevereiro-2022.csv
8915271411 -rw-r--r--@ 1 valencar  staff   5.6M May 16 11:16 prouni.csv
8871475204 -rw-r--r--@ 1 valencar  staff   242B May 10  2022 ratings_saida.csv
8928423198 -rw-r--r--@ 1 valen

In [80]:
!pwd

/Users/valencar/Dropbox/AULAS-UEPB-2023/Alunos-UEPB-TopicosEspeciaisEmBancoDeDados/Python-Para-Analise-de-Dados/MANHA


In [81]:
!cp /Users/valencar/Dropbox/AULAS-UEPB-2023/Alunos-UEPB-TopicosEspeciaisEmBancoDeDados/Python-Para-Analise-de-Dados/MANHA/vinhos_classificacao.csv \
            /Users/valencar/Dropbox/apps-2023/vinho-classificacao

In [82]:
!ls -ilah /Users/valencar/Dropbox/apps-2023/vinho-classificacao

total 184
8928423031 drwxr-xr-x@  4 valencar  staff   128B Sep 23 16:48 .
8902529186 drwxr-xr-x@ 30 valencar  staff   960B Sep 23 16:43 ..
8928423095 -rw-r--r--@  1 valencar  staff     0B Sep 23 16:44 app.py
8928423276 -rw-r--r--@  1 valencar  staff    90K Sep 23 16:48 vinhos_classificacao.csv


In [10]:
winedf.quality.unique()

array([5, 6, 7, 4, 8, 3])

In [11]:
winedf.quality.value_counts()

quality
5    681
6    638
7    199
4     53
8     18
3     10
Name: count, dtype: int64

In [12]:
winedf.quality.value_counts() / len(winedf) * 100

quality
5    42.589118
6    39.899937
7    12.445278
4     3.314572
8     1.125704
3     0.625391
Name: count, dtype: float64

## As classes estão DESBALANCEADAS

## Transformação de Dados
### classe 4 e classe 3 tem poucos dados -> colocar as tuplas (registros/linha) na classe 5

In [13]:
df = winedf.copy()
df.head()

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0            7.4              0.70         0.00             1.9      0.076   
1            7.8              0.88         0.00             2.6      0.098   
2            7.8              0.76         0.04             2.3      0.092   
3           11.2              0.28         0.56             1.9      0.075   
4            7.4              0.70         0.00             1.9      0.076   

   free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                 11.0                  34.0   0.9978  3.51       0.56   
1                 25.0                  67.0   0.9968  3.20       0.68   
2                 15.0                  54.0   0.9970  3.26       0.65   
3                 17.0                  60.0   0.9980  3.16       0.58   
4                 11.0                  34.0   0.9978  3.51       0.56   

   alcohol  quality  
0      9.4        5  
1      9.8        5  
2      9.8        5  
3      9.8        6  
4      9.4        5

In [14]:
# df['quality'] = df['quality'].apply(lambda x : 5 if x == 4 else x) 
# df['quality'].unique()

In [15]:
# df['quality'] = df['quality'].apply(lambda x : 5 if x == 3 else x) 
# df['quality'].unique()

In [16]:
df['quality'].value_counts()

quality
5    681
6    638
7    199
4     53
8     18
3     10
Name: count, dtype: int64

In [17]:
# df['quality'] = df['quality'].apply(lambda x : 7 if x == 8 else x) 
# df['quality'].unique()

In [18]:
df['quality'].value_counts()

quality
5    681
6    638
7    199
4     53
8     18
3     10
Name: count, dtype: int64

In [19]:
df['quality'].value_counts() / len(df) * 100

quality
5    42.589118
6    39.899937
7    12.445278
4     3.314572
8     1.125704
3     0.625391
Name: count, dtype: float64

In [20]:
winedf.quality.value_counts() / len(winedf) * 100

quality
5    42.589118
6    39.899937
7    12.445278
4     3.314572
8     1.125704
3     0.625391
Name: count, dtype: float64

In [21]:
df.head()

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0            7.4              0.70         0.00             1.9      0.076   
1            7.8              0.88         0.00             2.6      0.098   
2            7.8              0.76         0.04             2.3      0.092   
3           11.2              0.28         0.56             1.9      0.075   
4            7.4              0.70         0.00             1.9      0.076   

   free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                 11.0                  34.0   0.9978  3.51       0.56   
1                 25.0                  67.0   0.9968  3.20       0.68   
2                 15.0                  54.0   0.9970  3.26       0.65   
3                 17.0                  60.0   0.9980  3.16       0.58   
4                 11.0                  34.0   0.9978  3.51       0.56   

   alcohol  quality  
0      9.4        5  
1      9.8        5  
2      9.8        5  
3      9.8        6  
4      9.4        5

In [22]:
df[ df.quality == 7 ][:6]

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
7              7.3              0.65         0.00             1.2      0.065   
8              7.8              0.58         0.02             2.0      0.073   
16             8.5              0.28         0.56             1.8      0.092   
37             8.1              0.38         0.28             2.1      0.066   
62             7.5              0.52         0.16             1.9      0.085   
128            8.0              0.59         0.16             1.8      0.065   

     free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
7                   15.0                  21.0   0.9946  3.39       0.47   
8                    9.0                  18.0   0.9968  3.36       0.57   
16                  35.0                 103.0   0.9969  3.30       0.75   
37                  13.0                  30.0   0.9968  3.23       0.73   
62                  12.0                  35.0   0.9968  3.38       0.62   
128                  3.0                  16.0   0.9962  3.42       0.92   

     alcohol  quality  
7       10.0        7  
8        9.5        7  
16      10.5        7  
37       9.7        7  
62       9.5        7  
128     10.5        7

# Separação dos dados de entrada (X) e dado de Saída (y)

In [23]:
y = winedf["quality"]
X = winedf.drop(["quality"], axis=1)

X.head()

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0            7.4              0.70         0.00             1.9      0.076   
1            7.8              0.88         0.00             2.6      0.098   
2            7.8              0.76         0.04             2.3      0.092   
3           11.2              0.28         0.56             1.9      0.075   
4            7.4              0.70         0.00             1.9      0.076   

   free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                 11.0                  34.0   0.9978  3.51       0.56   
1                 25.0                  67.0   0.9968  3.20       0.68   
2                 15.0                  54.0   0.9970  3.26       0.65   
3                 17.0                  60.0   0.9980  3.16       0.58   
4                 11.0                  34.0   0.9978  3.51       0.56   

   alcohol  
0      9.4  
1      9.8  
2      9.8  
3      9.8  
4      9.4

In [24]:
y.head()

0    5
1    5
2    5
3    6
4    5
Name: quality, dtype: int64

In [25]:
model

Pipeline(steps=[('scaler', StandardScaler()), ('SVM', SVC())])

In [26]:
X[:3]

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0            7.4              0.70         0.00             1.9      0.076   
1            7.8              0.88         0.00             2.6      0.098   
2            7.8              0.76         0.04             2.3      0.092   

   free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                 11.0                  34.0   0.9978  3.51       0.56   
1                 25.0                  67.0   0.9968  3.20       0.68   
2                 15.0                  54.0   0.9970  3.26       0.65   

   alcohol  
0      9.4  
1      9.8  
2      9.8

In [27]:
labels = model.predict(X[:3])

In [28]:
labels

array([5, 5, 5])

# Vamos fazer o nosso modelo

In [29]:
X.head()

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0            7.4              0.70         0.00             1.9      0.076   
1            7.8              0.88         0.00             2.6      0.098   
2            7.8              0.76         0.04             2.3      0.092   
3           11.2              0.28         0.56             1.9      0.075   
4            7.4              0.70         0.00             1.9      0.076   

   free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                 11.0                  34.0   0.9978  3.51       0.56   
1                 25.0                  67.0   0.9968  3.20       0.68   
2                 15.0                  54.0   0.9970  3.26       0.65   
3                 17.0                  60.0   0.9980  3.16       0.58   
4                 11.0                  34.0   0.9978  3.51       0.56   

   alcohol  
0      9.4  
1      9.8  
2      9.8  
3      9.8  
4      9.4

In [30]:
from sklearn.ensemble import AdaBoostClassifier

clf = AdaBoostClassifier(n_estimators=300)
clf

AdaBoostClassifier(n_estimators=300)

In [31]:
from sklearn.tree import DecisionTreeClassifier

tree = DecisionTreeClassifier(
          max_depth=1,
          random_state=42)
tree = tree.fit(X, y)

In [32]:
from sklearn.svm import SVC

my_base_model= SVC()
ada = AdaBoostClassifier(
           base_estimator= my_base_model, #my_base_modeltree,
           n_estimators=500,
           learning_rate=0.5,
           algorithm='SAMME',
           random_state=42)

# Separação dos dados em Treino e Teste

In [33]:
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=65)

x_train.shape, x_test.shape

((1279, 11), (320, 11))

In [34]:
# O Algortimo XGBoost - Algoritmo Ensemble baseado em Árvores de Decisão

In [35]:
# Install
#!pip install -q xgboost

In [36]:
import xgboost as xgb

# Preparação dos dados de Saída

In [37]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
#y_train = le.fit_transform(y_train)
#y_test = le.fit_transform(y_test)

In [38]:
set(y_train)

{3, 4, 5, 6, 7, 8}

# Treinar o modelo com dados de entrada (X) e atributo de saída (y)

In [39]:
import numpy as np

In [40]:
%%time 
# treinar o modelo XGboost

# Preparar os dados para o algoritmo XGBoost - tranformar os dados
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y_train_XGBoost = le.fit_transform(y_train)

learning_rate = 1.1   
xgb_classifier = xgb.XGBClassifier(eta = learning_rate , n_estimators=200) # min_child_weight=6
xgb_classifier.fit(x_train.values, y_train_XGBoost)
xgb_classifier

CPU times: user 3.98 s, sys: 253 ms, total: 4.23 s
Wall time: 2.09 s


XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, early_stopping_rounds=None,
              enable_categorical=False, eta=1.1, eval_metric=None,
              feature_types=None, gamma=None, gpu_id=None, grow_policy=None,
              importance_type=None, interaction_constraints=None,
              learning_rate=None, max_bin=None, max_cat_threshold=None,
              max_cat_to_onehot=None, max_delta_step=None, max_depth=None,
              max_leaves=None, min_child_weight=None, missing=nan,
              monotone_constraints=None, n_estimators=200, n_jobs=None,
              num_parallel_tree=None, objective='multi:softprob', ...)

In [41]:
# modelo pré-treinado
model

Pipeline(steps=[('scaler', StandardScaler()), ('SVM', SVC())])

## Comparando os 2 modelos - Métricas

In [69]:
from sklearn.metrics import confusion_matrix, accuracy_score

y_pred_XGBoost = xgb_classifier.predict(x_test)
y_pred_XGBoost = le.inverse_transform(y_pred_XGBoost)
acc_XGBoost = accuracy_score(y_test, y_pred_XGBoost)
print('Acurácia do modelo XGBoost:', acc_XGBoost)
cm = confusion_matrix(y_test, y_pred_XGBoost)
print('Matriz de Confusão - XGBoost:\n',cm)

print('============================================')

y_prev_model_SVC = model.predict(x_test)
acc_SVC = accuracy_score(y_test, y_prev_model_SVC)
print('Acurácia do modelo SVC:', acc_SVC)
cm = confusion_matrix(y_test, y_prev_model_SVC)
print('Matriz de Confusão - Modelo Pré-treinado:\n',cm)

Acurácia do modelo XGBoost: 0.675
Matriz de Confusão - XGBoost:
 [[  0   1   1   0   0   0]
 [  0   1   4   1   0   0]
 [  1   2 106  30   1   0]
 [  0   2  30  84   8   1]
 [  0   0   1  18  25   0]
 [  0   0   0   0   3   0]]
Acurácia do modelo SVC: 0.640625
Matriz de Confusão - Modelo Pré-treinado:
 [[  0   0   1   1   0   0]
 [  0   0   6   0   0   0]
 [  0   0 110  30   0   0]
 [  0   0  44  77   4   0]
 [  0   0   2  24  18   0]
 [  0   0   0   3   0   0]]


In [43]:
labels = model.predict(X[:3])
labels

array([5, 5, 5])

In [44]:
labels = xgb_classifier.predict(X[:3])
labels

array([2, 2, 2])

In [45]:
le.inverse_transform(labels)

array([5, 5, 5])

# Verificar a acurácia - taxa de acertos

In [46]:
modelo = xgb_classifier

In [47]:
modelo.get_params()

{'objective': 'multi:softprob',
 'use_label_encoder': None,
 'base_score': None,
 'booster': None,
 'callbacks': None,
 'colsample_bylevel': None,
 'colsample_bynode': None,
 'colsample_bytree': None,
 'early_stopping_rounds': None,
 'enable_categorical': False,
 'eval_metric': None,
 'feature_types': None,
 'gamma': None,
 'gpu_id': None,
 'grow_policy': None,
 'importance_type': None,
 'interaction_constraints': None,
 'learning_rate': None,
 'max_bin': None,
 'max_cat_threshold': None,
 'max_cat_to_onehot': None,
 'max_delta_step': None,
 'max_depth': None,
 'max_leaves': None,
 'min_child_weight': None,
 'missing': nan,
 'monotone_constraints': None,
 'n_estimators': 200,
 'n_jobs': None,
 'num_parallel_tree': None,
 'predictor': None,
 'random_state': None,
 'reg_alpha': None,
 'reg_lambda': None,
 'sampling_method': None,
 'scale_pos_weight': None,
 'subsample': None,
 'tree_method': None,
 'validate_parameters': None,
 'verbosity': None,
 'eta': 1.1}

In [48]:
modelo.get_metadata_routing()

{'fit': {'sample_weight': None, 'base_margin': None, 'eval_set': None, 'eval_metric': None, 'early_stopping_rounds': None, 'verbose': None, 'xgb_model': None, 'sample_weight_eval_set': None, 'base_margin_eval_set': None, 'feature_weights': None, 'callbacks': None}, 'predict': {'output_margin': None, 'ntree_limit': None, 'validate_features': None, 'base_margin': None, 'iteration_range': None}, 'predict_proba': {'ntree_limit': None, 'validate_features': None, 'base_margin': None, 'iteration_range': None}, 'score': {'sample_weight': None}}

In [49]:
dir(modelo)

['_Booster',
 '__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__setstate__',
 '__sizeof__',
 '__sklearn_clone__',
 '__sklearn_is_fitted__',
 '__slotnames__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 '_build_request_for_signature',
 '_can_use_inplace_predict',
 '_check_feature_names',
 '_check_n_features',
 '_configure_fit',
 '_create_dmatrix',
 '_early_stopping_attr',
 '_estimator_type',
 '_get_default_requests',
 '_get_iteration_range',
 '_get_metadata_request',
 '_get_param_names',
 '_get_tags',
 '_get_type',
 '_more_tags',
 '_repr_html_',
 '_repr_html_inner',
 '_repr_mimebundle_',
 '_set_evaluation_result',
 '_validate_data',
 '_validate_params',
 'apply',
 'base_score',
 'best_iteration',
 'best_ntree_

In [50]:
modelo.classes_

array([0, 1, 2, 3, 4, 5])

In [51]:
model.n_features_in_

11

In [52]:
modelo.feature_importances_

array([0.06292934, 0.0886521 , 0.05562941, 0.08738615, 0.06594306,
       0.07471896, 0.11073156, 0.05286177, 0.06052837, 0.1208677 ,
       0.21975154], dtype=float32)

In [53]:
X.head()

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0            7.4              0.70         0.00             1.9      0.076   
1            7.8              0.88         0.00             2.6      0.098   
2            7.8              0.76         0.04             2.3      0.092   
3           11.2              0.28         0.56             1.9      0.075   
4            7.4              0.70         0.00             1.9      0.076   

   free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                 11.0                  34.0   0.9978  3.51       0.56   
1                 25.0                  67.0   0.9968  3.20       0.68   
2                 15.0                  54.0   0.9970  3.26       0.65   
3                 17.0                  60.0   0.9980  3.16       0.58   
4                 11.0                  34.0   0.9978  3.51       0.56   

   alcohol  
0      9.4  
1      9.8  
2      9.8  
3      9.8  
4      9.4

In [54]:
atributos = list(X.columns.values)
print(atributos)

['fixed acidity', 'volatile acidity', 'citric acid', 'residual sugar', 'chlorides', 'free sulfur dioxide', 'total sulfur dioxide', 'density', 'pH', 'sulphates', 'alcohol']


In [55]:
modelo.feature_importances_

array([0.06292934, 0.0886521 , 0.05562941, 0.08738615, 0.06594306,
       0.07471896, 0.11073156, 0.05286177, 0.06052837, 0.1208677 ,
       0.21975154], dtype=float32)

In [56]:
dfi = pd.DataFrame( {'atributos' : atributos, 'importancia':  modelo.feature_importances_ })
dfi

atributos  importancia
0          fixed acidity     0.062929
1       volatile acidity     0.088652
2            citric acid     0.055629
3         residual sugar     0.087386
4              chlorides     0.065943
5    free sulfur dioxide     0.074719
6   total sulfur dioxide     0.110732
7                density     0.052862
8                     pH     0.060528
9              sulphates     0.120868
10               alcohol     0.219752

In [57]:
dfo = dfi.sort_values(by='importancia', ascending=False).reset_index(drop=True)
dfo

atributos  importancia
0                alcohol     0.219752
1              sulphates     0.120868
2   total sulfur dioxide     0.110732
3       volatile acidity     0.088652
4         residual sugar     0.087386
5    free sulfur dioxide     0.074719
6              chlorides     0.065943
7          fixed acidity     0.062929
8                     pH     0.060528
9            citric acid     0.055629
10               density     0.052862

In [71]:
atributos_importantes = dfo[:9]
atributos_importantes 

atributos  importancia
0               alcohol     0.219752
1             sulphates     0.120868
2  total sulfur dioxide     0.110732
3      volatile acidity     0.088652
4        residual sugar     0.087386
5   free sulfur dioxide     0.074719
6             chlorides     0.065943
7         fixed acidity     0.062929
8                    pH     0.060528

In [72]:
atributos_mais_importantes = list(atributos_importantes.atributos)
atributos_mais_importantes 

['alcohol',
 'sulphates',
 'total sulfur dioxide',
 'volatile acidity',
 'residual sugar',
 'free sulfur dioxide',
 'chlorides',
 'fixed acidity',
 'pH']

In [73]:
X.tail()

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
1594            6.2             0.600         0.08             2.0      0.090   
1595            5.9             0.550         0.10             2.2      0.062   
1596            6.3             0.510         0.13             2.3      0.076   
1597            5.9             0.645         0.12             2.0      0.075   
1598            6.0             0.310         0.47             3.6      0.067   

      free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
1594                 32.0                  44.0  0.99490  3.45       0.58   
1595                 39.0                  51.0  0.99512  3.52       0.76   
1596                 29.0                  40.0  0.99574  3.42       0.75   
1597                 32.0                  44.0  0.99547  3.57       0.71   
1598                 18.0                  42.0  0.99549  3.39       0.66   

      alcohol  
1594     10.5  
1595     11.2  
1596     11.0  
1597     10.2  
1598     11.0

In [74]:
X[ X.index == 1597]

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
1597            5.9             0.645         0.12             2.0      0.075   

      free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
1597                 32.0                  44.0  0.99547  3.57       0.71   

      alcohol  
1597     10.2

In [75]:
x1 = X[ X.index == 1597].values
x1

array([[ 5.9    ,  0.645  ,  0.12   ,  2.     ,  0.075  , 32.     ,
        44.     ,  0.99547,  3.57   ,  0.71   , 10.2    ]])

In [76]:
import numpy as np

In [77]:
modelo.predict(x1)

array([2])

In [78]:
le.inverse_transform(modelo_lido.predict(x1))

array([5])

# Deploy da Parte1 
## Salvar o modelo treinado

In [65]:
import pickle as pkl

filehandler = open("ModeloXGBoost.pkl" ,"wb")
pkl.dump(modelo,filehandler)
filehandler.close()

!ls -lah *.pkl

-rw-r--r--@ 1 valencar  staff   1.2M Sep 23 12:16 ModeloXGBoost.pkl
-rw-r--r--@ 1 valencar  staff   200K Sep 21 12:48 modeloAdaboost.pkl


In [66]:
!head ModeloXGBoost.pkl

XGBClassifier���)��}�(�use_label_encoder�N�n_estimators�KȌ	objective��multi:softprob��	max_depth�N�
learning_rate�N�	verbosity�N�booster�N�tree_method�N�gamma�N�min_child_weight�N�max_delta_step�N�	subsample�N�sampling_method�N�colsample_bytree�N�colsample_bylevel�N�colsample_bynode�N�	reg_alpha�N�
reg_lambda�N�scale_pos_weight�N�
feature_types�N�max_cat_to_onehot�N�max_cat_threshold�N�eval_metric�N�early_stopping_rounds�N�	callbacks�N�kwargs�}��eta�G?񙙙���sclasses_��numpy.core.multiarray��_reconstruct����numpy��ndarray���K��Cb���R�(KK��h5�dtype����i8�����R�(K�<�NNNJ����J����Kt�b�C0�t�b�
opt_dense_colSL1}Ltrain_param{LalphaSL0L	cache_optSL1Lcolsample_bylevelSL1Lcolsample_bynodeSL1Lcolsample_bytreeSL1LetaSLLvalidate_parametersSL1}Lgradient_booster{Lgbtree_model_param{L

# Carregar o modelo treinado

In [67]:
file = "ModeloXGBoost.pkl"
with open(file, 'rb') as f:
    modelo_lido = pkl.load(f)

   # df=pickle.load(open('df.p','rb'))
    
modelo_lido

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, early_stopping_rounds=None,
              enable_categorical=False, eta=1.1, eval_metric=None,
              feature_types=None, gamma=None, gpu_id=None, grow_policy=None,
              importance_type=None, interaction_constraints=None,
              learning_rate=None, max_bin=None, max_cat_threshold=None,
              max_cat_to_onehot=None, max_delta_step=None, max_depth=None,
              max_leaves=None, min_child_weight=None, missing=nan,
              monotone_constraints=None, n_estimators=200, n_jobs=None,
              num_parallel_tree=None, objective='multi:softprob', ...)

In [68]:
le.inverse_transform(modelo_lido.predict(x1))[0]

5

In [83]:
!ls -ilha *.pkl

8928404177 -rw-r--r--@ 1 valencar  staff   1.2M Sep 23 12:16 ModeloXGBoost.pkl
8928237317 -rw-r--r--@ 1 valencar  staff   200K Sep 21 12:48 modeloAdaboost.pkl


In [89]:
!cp ModeloXGBoost.pkl  /Users/valencar/Dropbox/apps-2023/vinho-classificacao

In [90]:
!ls -ilha ModeloXGBoost.pkl

8928404177 -rw-r--r--@ 1 valencar  staff   1.2M Sep 23 12:16 ModeloXGBoost.pkl


In [96]:
set(y)

{3, 4, 5, 6, 7, 8}

In [112]:
df.density.min(), df.density.mean(), df.density.max()

(0.99007, 0.9967466791744841, 1.00369)

In [109]:
atributos = list(df.columns.values)
dic_atributos_valores = {}
for atributo in atributos:
    min, media, max = df[atributo].min(), df[atributo].mean(), df[atributo].max()
    print('atributo:', atributo, ':  ', min, media, max)
    step = (max - min) / media
    print('step:', step)
    dic_atributos_valores[atributo] = {'min': min, 'media': media, 'max': max, 'step': step }

print('='* 100)
dic_atributos_valores

atributo: fixed acidity :   4.6 8.31963727329581 15.9
step: 1.3582322917214786
atributo: volatile acidity :   0.12 0.5278205128205128 1.58
step: 2.766091814427982
atributo: citric acid :   0.0 0.2709756097560976 1.0
step: 3.6903690369036903
atributo: residual sugar :   0.9 2.53880550343965 15.5
step: 5.750735919005801
atributo: chlorides :   0.012 0.08746654158849279 0.611
step: 6.8483329639136565
atributo: free sulfur dioxide :   1.0 15.874921826141339 72.0
step: 4.472462968799244
atributo: total sulfur dioxide :   6.0 46.46779237023139 289.0
step: 6.090239832036823
atributo: density :   0.99007 0.9967466791744841 1.00369
step: 0.01366445485555085
atributo: pH :   2.74 3.3111131957473416 4.01
step: 0.3835568054970563
atributo: sulphates :   0.33 0.6581488430268917 2.0
step: 2.537419943366465
atributo: alcohol :   8.4 10.422983114446529 14.9
step: 0.6236218488151275
atributo: quality :   3 5.6360225140712945 8
step: 0.8871504660452729


{'fixed acidity': {'min': 4.6,
  'media': 8.31963727329581,
  'max': 15.9,
  'step': 1.3582322917214786},
 'volatile acidity': {'min': 0.12,
  'media': 0.5278205128205128,
  'max': 1.58,
  'step': 2.766091814427982},
 'citric acid': {'min': 0.0,
  'media': 0.2709756097560976,
  'max': 1.0,
  'step': 3.6903690369036903},
 'residual sugar': {'min': 0.9,
  'media': 2.53880550343965,
  'max': 15.5,
  'step': 5.750735919005801},
 'chlorides': {'min': 0.012,
  'media': 0.08746654158849279,
  'max': 0.611,
  'step': 6.8483329639136565},
 'free sulfur dioxide': {'min': 1.0,
  'media': 15.874921826141339,
  'max': 72.0,
  'step': 4.472462968799244},
 'total sulfur dioxide': {'min': 6.0,
  'media': 46.46779237023139,
  'max': 289.0,
  'step': 6.090239832036823},
 'density': {'min': 0.99007,
  'media': 0.9967466791744841,
  'max': 1.00369,
  'step': 0.01366445485555085},
 'pH': {'min': 2.74,
  'media': 3.3111131957473416,
  'max': 4.01,
  'step': 0.3835568054970563},
 'sulphates': {'min': 0.33,
 

In [92]:
atributos = list(df.columns.values)
atributos.remove('quality')


i = 0
campos_atributos = np.array(len(atributos))
for atributo in atributos:
    campos_atributos[i] = i * 10
    i += 1
campos_atributos

IndexError: too many indices for array: array is 0-dimensional, but 1 were indexed

In [93]:
atributos 

['fixed acidity',
 'volatile acidity',
 'citric acid',
 'residual sugar',
 'chlorides',
 'free sulfur dioxide',
 'total sulfur dioxide',
 'density',
 'pH',
 'sulphates',
 'alcohol']

In [94]:
len(atributos)

11

In [95]:
print(atributos)

['fixed acidity', 'volatile acidity', 'citric acid', 'residual sugar', 'chlorides', 'free sulfur dioxide', 'total sulfur dioxide', 'density', 'pH', 'sulphates', 'alcohol']
